### ISSUE TITLE
No way to get "failed" payment status

### ISSUE THREAD

**Issue by TRiV07** [umbraco/Umbraco.Commerce.PaymentProviders.PayPal#4]
I'm trying to capture payment failures from PayPal, to let purchaser know that payment is failed.
PayPal successfully redirects purchasers back to the predefined receipt page, but webhook callback is unable to correctly handle capture.
It looks like on the [PayPalCheckoutOneTimePaymentProvider capture step](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.PayPal/blob/b12d07b91f5de8df2c43eb6529cd889b04ebf78b/src/Umbraco.Commerce.PaymentProviders.PayPal/PayPalCheckoutOneTimePaymentProvider.cs#L171) provider throws and exception:

`Flurl.Http.FlurlHttpException: Call failed with status code 422 (Unprocessable Entity): POST https://api.paypal.com/v2/checkout/orders/XXXXXXXXXXXXXXXXX/capture at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken) at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task``1 response) at Umbraco.Commerce.PaymentProviders.PayPal.Api.PayPalClient.<>c.<<CaptureOrderAsync>b__8_0>d.MoveNext() --- End of stack trace from previous location --- at Umbraco.Commerce.PaymentProviders.PayPal.Api.PayPalClient.RequestAsync[TResult](String url, Func``3 func, CancellationToken cancellationToken) at Umbraco.Commerce.PaymentProviders.PayPal.Api.PayPalClient.RequestAsync[TResult](String url, Func``3 func, CancellationToken cancellationToken) at Umbraco.Commerce.PaymentProviders.PayPal.Api.PayPalClient.CaptureOrderAsync(String orderId, CancellationToken cancellationToken) at Umbraco.Commerce.PaymentProviders.PayPal.PayPalCheckoutOneTimePaymentProvider.ProcessCallbackAsync(PaymentProviderContext``1 ctx, CancellationToken cancellationToken)`

It would be helpful to update order transaction to failed when capture is failed.

I also tried to manually fetch payment status by [FetchPaymentStatusAsync method](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.PayPal/blob/b12d07b91f5de8df2c43eb6529cd889b04ebf78b/src/Umbraco.Commerce.PaymentProviders.PayPal/PayPalCheckoutOneTimePaymentProvider.cs#L220) with no success because `"PayPalOrderId"` is not exists (it must be provided by [ProcessCallbackAsync method](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.PayPal/blob/b12d07b91f5de8df2c43eb6529cd889b04ebf78b/src/Umbraco.Commerce.PaymentProviders.PayPal/PayPalCheckoutOneTimePaymentProvider.cs#L134) that always fails.

**Comment by umbracotrd** [comment]
Hello @TRiV07 , thank you for taking time to report this issue to us.

My proposal is that we're going to create an order in error status whenever the payment is declined by PayPal. By doing that, you can hook up to Umbraco Commerce events (https://docs.umbraco.com/umbraco-commerce/key-concepts/events#notification-events) to notify the buyer via email or other methods.

The change details can be seen in #6 .

Unless you have further suggestions, that will be our solution for this issue.

**Comment by TRiV07** [comment]
Hi @umbracotrd

Thank you for your solution! Changing order status to error is what I expected, and I am happy to close the issue.

**Comment by umbracotrd** [comment]
@TRiV07 : I've pushed the fix to `13.1.1`, `12.0.1` and `10.0.1`. It should be searchable on nuget after an hour or so. Please check them out and tell me if it solve your issue.

**Comment by TRiV07** [comment]
Hi @umbracotrd

Thanks again. Let me test it.

**Comment by TRiV07** [comment]
Hi @umbracotrd,

Just wanted to confirm that the update works as expected.

Thanks,
Alex
